import {StyleSheet} from 'react-native';
import {Colors} from '../../colors/Colors';
import {Fonts} from '../../fonts/fonts';
export const styles = StyleSheet.create({
  Board: {
    flex: 1,
    backgroundColor: Colors.Dblue,
    padding: 20,
    alignItems: 'center',
  },
  player: {
    fontSize: 28,
    fontFamily: Fonts.Ebold,
    color: Colors.white,
    marginVertical: 4,
  },
  Title: {
    fontFamily: Fonts.bold,
    fontSize: 30,
    color: Colors.white,
    marginVertical: '26%',
    textAlign: 'center',
    letterSpacing: 1,
    lineHeight: 50,
  },
  sepertText: {
    fontSize: 20,
    fontFamily: Fonts.Ebold,
    color: Colors.white,
    marginVertical: '10%',
  },
  btn: {
    width: 190,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 90,
    elevation: 7,
  },
  gridContain: {
    flex: 1,
    alignItems: 'center',
    padding: 20,
  },
  boardContainer: {
    width: '100%',
    height: '50%',
    flexWrap: 'wrap',
    borderRadius: 20,
    elevation: 7,
  },
  squares: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '33%',
    height: '33%',
    borderRadius: 20,
  },
  line1: {
    width: '80%',
    height: 1,
    backgroundColor: Colors.Dblue,
    position: 'absolute',
    alignSelf: 'center',
    top: '33%',
    elevation: 7,
  },
  line2: {
    width: '80%',
    height: 1,
    backgroundColor: Colors.Dblue,
    position: 'absolute',
    alignSelf: 'center',
    bottom: '33%',
    elevation: 7,
  },
  line3: {
    width: 1,
    height: '70%',
    backgroundColor: Colors.Dblue,
    position: 'absolute',
    alignSelf: 'center',
    top: '16%',
    left: '33%',
    elevation: 7,
  },
  line4: {
    width: 1,
    height: '70%',
    backgroundColor: Colors.Dblue,
    position: 'absolute',
    alignSelf: 'center',
    right: '33%',
    top: '16%',
    elevation: 7,
  },
  Mark: {
    fontSize: 80,
    alignSelf: 'center',
    fontFamily: Fonts.bold,
    color: Colors.white,
  },
  Headtxt: {
    fontFamily: Fonts.bold,
    fontSize: 30,
    textAlign: 'center',
    lineHeight: 50,
    letterSpacing: 1,
    color: Colors.white,
    alignSelf: 'center',
  },
  Mock: {
    fontSize: 22,
    fontFamily: Fonts.bold,
    color: Colors.icon2,
    alignSelf: 'center',
    textAlign: 'center',
    marginTop: '10%',
  },
});
